<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;

class TestCase extends Illuminate\Foundation\Testing\TestCase
{
    /**
     * @var
     */
    protected $authentication_header;
    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://localhost';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }

    /**
     * Prepare for test
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Input::server('HTTP_ACCEPT', '*/*');
        $this->authentication_header = [
            'HTTP_ACCEPT' => 'application/json'
        ];
        DB::beginTransaction();
    }

    /**
     * Revert DB changes after test
     */
    public function tearDown()
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
